<?php
return array(
	'title'      => esc_html__( 'Logo Setting', 'rufers' ),
	'id'         => 'logo_setting',
	'desc'       => '',
	'subsection' => false,
	'fields'     => array(
		array(
			'id'       => 'image_favicon',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Favicon', 'rufers' ),
			'subtitle' => esc_html__( 'Insert site favicon image', 'rufers' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/favicon/favicon.ico' ),
		),
		array(
            'id' => 'normal_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Light Logo', 'rufers'),
            'default' => true,
        ),
		array(
			'id'       => 'light_image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Light Color Logo', 'rufers' ),
			'subtitle' => esc_html__( 'Insert site Light Color logo image', 'rufers' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/resources/logo.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'light_normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Light Color Logo Dimentions', 'rufers' ),
			'subtitle' => esc_html__( 'Select Light Color Logo Dimentions', 'rufers' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show2',
            'type' => 'switch',
            'title' => esc_html__('Enable Sidebar Info Logo', 'rufers'),
            'default' => true,
        ),
		array(
			'id'       => 'sidebar_image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Sidebar Info Logo', 'rufers' ),
			'subtitle' => esc_html__( 'Insert site Sidebar Info logo image', 'rufers' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/resources/logo-2.png' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
			'id'       => 'sidebar_normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Sidebar Info Logo Dimentions', 'rufers' ),
			'subtitle' => esc_html__( 'Select Sidebar Info Dimentions', 'rufers' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show2', '=', true ),
		),
		array(
            'id' => 'normal_logo_show3',
            'type' => 'switch',
            'title' => esc_html__('Enable Sticky Header Logo', 'rufers'),
            'default' => true,
        ),
		array(
			'id'       => 'sticky_image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Sticky Header Logo', 'rufers' ),
			'subtitle' => esc_html__( 'Insert site Sticky Header logo image', 'rufers' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/resources/sticky-logo.png' ),
			'required' => array( 'normal_logo_show3', '=', true ),
		),
		array(
			'id'       => 'sticky_normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Sticky Header Logo Dimentions', 'rufers' ),
			'subtitle' => esc_html__( 'Select Sticky Header Logo Dimentions', 'rufers' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show3', '=', true ),
		),
		array(
            'id' => 'color_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Sticky Colored Logo', 'rufers'),
            'default' => true,
        ),
		array(
			'id'       => 'sticky_color_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Sticky Colored Logo', 'rufers' ),
			'subtitle' => esc_html__( 'Insert site Sticky Colored logo image', 'rufers' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/resources/sticky-logo.png' ),
			'required' => array( 'color_logo_show', '=', true ),
		),
		array(
			'id'       => 'sticky_color_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Sticky Colored Logo Dimentions', 'rufers' ),
			'subtitle' => esc_html__( 'Select Sticky Colored Logo Dimentions', 'rufers' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'color_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show4',
            'type' => 'switch',
            'title' => esc_html__('Enable Mobile View Logo', 'rufers'),
            'default' => true,
        ),
		array(
			'id'       => 'mobile_image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Mobile View Logo', 'rufers' ),
			'subtitle' => esc_html__( 'Insert site Mobile View logo image', 'rufers' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/resources/mobilemenu-logo.png' ),
			'required' => array( 'normal_logo_show4', '=', true ),
		),
		array(
			'id'       => 'mobile_normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Mobile View Logo Dimentions', 'rufers' ),
			'subtitle' => esc_html__( 'Select Mobile View Logo Dimentions', 'rufers' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show4', '=', true ),
		),
		array(
			'id'       => 'logo_settings_section_end',
			'type'     => 'section',
			'indent'      => false,
		),
	),
);
